### ISSUE TITLE
Node-Red ver 4

### ISSUE THREAD

**Issue by Unpuertomex** [alexkn/node-red-contrib-dlna#31]
I have been using this node for years. However, with an upgrade to node-red version 4 it no longer works, any chance of updating this node to be compatible with the latest version of node-red?

**Comment by Barabba11** [comment]
Hi, can you please write here an example how are you using it? WHat parameters exactly to pass? How should be formatted the URL? Thank you!

**Comment by Unpuertomex** [comment]
> Hi, can you please write here an example how are you using it? WHat parameters exactly to pass? How should be formatted the URL? Thank you!

Here is how I have it working using a function node: 
```
{
var msg1 = {payload: {"action": "setvolume", "volume": "75"}}
var msg2 = {payload: {"action": "load", "url": "http://192.168.109.178/local/end-level-beep_C_major.wav"}}
node.status({fill:"red",shape:"dot",text:"test"})
node.send(msg1); node.send(msg2);
}

and in the DLNA node I'm calling the speaker by IP I want to send to play out of: http://192.168.109.118:49152/description.xml

I hope this helps.

**Comment by Barabba11** [comment]
Hi! Thank you a lot for replying me! Your informations are really precious!
I'm trying locally eith Kodi, I've opened a tiny http server for serving files via http as you suggested and it works, I'm using Kodi as DLNA listener and I've enabled all the services inside itm unfortunately it is not listening on port 49152 as you suggested, 
I've tried to get infos but nothing helped me, so I tried to figure out myself, the way Kodi is discovered by DLNA apps from my phone is by TCP port 1179, but tryping it in your example returns error "Error: Request failed"
ON the modue I'm using this string http://127.0.0.1:1179/description.xml

Do you have kindly the chance to test your job on Kodi? Thank you very much!

**Comment by Unpuertomex** [comment]
Sorry, but I don't use Kodi in this manner. I stream directly to the speakers using Node-Red.

**Comment by Barabba11** [comment]
thank you anyway. Unfortunately Kodi has lot of unsolved things.. :(
