### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by jerod33** [alexkn/node-red-contrib-dlna#5]
Hi,
I get an error when using it "**Error: connect ECONNREFUSED** " and ip address from tv.
Can you tell me where the advise is.
Thank you Jarda

**Comment by alexkn** [comment]
Apparently your TV is refusing the connection.
Maybe you have to activate something on your TV.
I never tested it with TVs, I only use it with my av receiver.

**Comment by jerod33** [comment]
Thanks for the reply, I'm going to keep looking
